/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DescrizioneWhereUniqueInput } from "../../descrizione/base/DescrizioneWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { MuseoWhereUniqueInput } from "../../museo/base/MuseoWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
@InputType()
class OperaWhereInput {
  @ApiProperty({
    required: false,
    type: () => DescrizioneWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DescrizioneWhereUniqueInput)
  @IsOptional()
  @Field(() => DescrizioneWhereUniqueInput, {
    nullable: true,
  })
  descrizione?: DescrizioneWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  immagineOpera?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => MuseoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MuseoWhereUniqueInput)
  @IsOptional()
  @Field(() => MuseoWhereUniqueInput, {
    nullable: true,
  })
  museo?: MuseoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  titoloOpera?: StringNullableFilter;
}
export { OperaWhereInput };
