/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CapitoloService } from "../capitolo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CapitoloCreateInput } from "./CapitoloCreateInput";
import { CapitoloWhereInput } from "./CapitoloWhereInput";
import { CapitoloWhereUniqueInput } from "./CapitoloWhereUniqueInput";
import { CapitoloFindManyArgs } from "./CapitoloFindManyArgs";
import { CapitoloUpdateInput } from "./CapitoloUpdateInput";
import { Capitolo } from "./Capitolo";
import { DescrizioneFindManyArgs } from "../../descrizione/base/DescrizioneFindManyArgs";
import { Descrizione } from "../../descrizione/base/Descrizione";
import { DescrizioneWhereUniqueInput } from "../../descrizione/base/DescrizioneWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CapitoloControllerBase {
  constructor(
    protected readonly service: CapitoloService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Capitolo })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: CapitoloCreateInput): Promise<Capitolo> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        numero: true,
        testo: true,
        titolo: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Capitolo] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(CapitoloFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Capitolo[]> {
    const args = plainToClass(CapitoloFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        numero: true,
        testo: true,
        titolo: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Capitolo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CapitoloWhereUniqueInput
  ): Promise<Capitolo | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        numero: true,
        testo: true,
        titolo: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Capitolo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CapitoloWhereUniqueInput,
    @common.Body() data: CapitoloUpdateInput
  ): Promise<Capitolo | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          numero: true,
          testo: true,
          titolo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Capitolo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CapitoloWhereUniqueInput
  ): Promise<Capitolo | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          numero: true,
          testo: true,
          titolo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/descriziones")
  @ApiNestedQuery(DescrizioneFindManyArgs)
  async findManyDescriziones(
    @common.Req() request: Request,
    @common.Param() params: CapitoloWhereUniqueInput
  ): Promise<Descrizione[]> {
    const query = plainToClass(DescrizioneFindManyArgs, request.query);
    const results = await this.service.findDescriziones(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        operas: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/descriziones")
  async connectDescriziones(
    @common.Param() params: CapitoloWhereUniqueInput,
    @common.Body() body: DescrizioneWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      descriziones: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/descriziones")
  async updateDescriziones(
    @common.Param() params: CapitoloWhereUniqueInput,
    @common.Body() body: DescrizioneWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      descriziones: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/descriziones")
  async disconnectDescriziones(
    @common.Param() params: CapitoloWhereUniqueInput,
    @common.Body() body: DescrizioneWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      descriziones: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
