/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MuseoService } from "../museo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MuseoCreateInput } from "./MuseoCreateInput";
import { MuseoWhereInput } from "./MuseoWhereInput";
import { MuseoWhereUniqueInput } from "./MuseoWhereUniqueInput";
import { MuseoFindManyArgs } from "./MuseoFindManyArgs";
import { MuseoUpdateInput } from "./MuseoUpdateInput";
import { Museo } from "./Museo";
import { OperaFindManyArgs } from "../../opera/base/OperaFindManyArgs";
import { Opera } from "../../opera/base/Opera";
import { OperaWhereUniqueInput } from "../../opera/base/OperaWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MuseoControllerBase {
  constructor(
    protected readonly service: MuseoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Museo })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: MuseoCreateInput): Promise<Museo> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        denominazione: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Museo] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(MuseoFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Museo[]> {
    const args = plainToClass(MuseoFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        denominazione: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Museo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: MuseoWhereUniqueInput
  ): Promise<Museo | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        denominazione: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Museo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: MuseoWhereUniqueInput,
    @common.Body() data: MuseoUpdateInput
  ): Promise<Museo | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          denominazione: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Museo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: MuseoWhereUniqueInput
  ): Promise<Museo | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          denominazione: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Opera",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/operas")
  @ApiNestedQuery(OperaFindManyArgs)
  async findManyOperas(
    @common.Req() request: Request,
    @common.Param() params: MuseoWhereUniqueInput
  ): Promise<Opera[]> {
    const query = plainToClass(OperaFindManyArgs, request.query);
    const results = await this.service.findOperas(params.id, {
      ...query,
      select: {
        createdAt: true,

        descrizione: {
          select: {
            id: true,
          },
        },

        id: true,
        immagineOpera: true,

        museo: {
          select: {
            id: true,
          },
        },

        titoloOpera: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/operas")
  async connectOperas(
    @common.Param() params: MuseoWhereUniqueInput,
    @common.Body() body: OperaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operas: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/operas")
  async updateOperas(
    @common.Param() params: MuseoWhereUniqueInput,
    @common.Body() body: OperaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operas: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Museo",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/operas")
  async disconnectOperas(
    @common.Param() params: MuseoWhereUniqueInput,
    @common.Body() body: OperaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operas: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
