/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DescrizioneService } from "../descrizione.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DescrizioneCreateInput } from "./DescrizioneCreateInput";
import { DescrizioneWhereInput } from "./DescrizioneWhereInput";
import { DescrizioneWhereUniqueInput } from "./DescrizioneWhereUniqueInput";
import { DescrizioneFindManyArgs } from "./DescrizioneFindManyArgs";
import { DescrizioneUpdateInput } from "./DescrizioneUpdateInput";
import { Descrizione } from "./Descrizione";
import { CapitoloFindManyArgs } from "../../capitolo/base/CapitoloFindManyArgs";
import { Capitolo } from "../../capitolo/base/Capitolo";
import { CapitoloWhereUniqueInput } from "../../capitolo/base/CapitoloWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DescrizioneControllerBase {
  constructor(
    protected readonly service: DescrizioneService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Descrizione })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: DescrizioneCreateInput
  ): Promise<Descrizione> {
    return await this.service.create({
      data: {
        ...data,

        operas: data.operas
          ? {
              connect: data.operas,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        operas: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Descrizione] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DescrizioneFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Descrizione[]> {
    const args = plainToClass(DescrizioneFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        operas: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Descrizione })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DescrizioneWhereUniqueInput
  ): Promise<Descrizione | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        operas: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Descrizione })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DescrizioneWhereUniqueInput,
    @common.Body() data: DescrizioneUpdateInput
  ): Promise<Descrizione | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          operas: data.operas
            ? {
                connect: data.operas,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          operas: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Descrizione })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DescrizioneWhereUniqueInput
  ): Promise<Descrizione | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          operas: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Capitolo",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/capitolo")
  @ApiNestedQuery(CapitoloFindManyArgs)
  async findManyCapitolo(
    @common.Req() request: Request,
    @common.Param() params: DescrizioneWhereUniqueInput
  ): Promise<Capitolo[]> {
    const query = plainToClass(CapitoloFindManyArgs, request.query);
    const results = await this.service.findCapitolo(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        numero: true,
        testo: true,
        titolo: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/capitolo")
  async connectCapitolo(
    @common.Param() params: DescrizioneWhereUniqueInput,
    @common.Body() body: CapitoloWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      capitolo: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/capitolo")
  async updateCapitolo(
    @common.Param() params: DescrizioneWhereUniqueInput,
    @common.Body() body: CapitoloWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      capitolo: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Descrizione",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/capitolo")
  async disconnectCapitolo(
    @common.Param() params: DescrizioneWhereUniqueInput,
    @common.Body() body: CapitoloWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      capitolo: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
